{%set name = "factory_boy" %}
{%set version = "2.8.1" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "a6644e391a371be603aca8624f3dedbc5a2aa4622878c20494ba17abb4b171bb" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - fake-factory >=0.5.0

test:
  imports:
    - factory

about:
  home: https://github.com/rbarrois/factory_boy
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: "A versatile test fixtures replacement based on thoughtbot's factory_girl for Ruby."
  dev_url: https://github.com/rbarrois/factory_boy
  doc_url: https://factoryboy.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
