{% set name = "factory_boy" %}
{% set version = "2.10.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "bd5a096d0f102d79b6c78cef1c8c0b650f2e1a3ecba351c735c6d2df8dabd29c" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools >=0.8.0

  run:
    - python
    - faker >=0.7.0

test:
  imports:
    - factory

about:
  home: https://github.com/FactoryBoy/factory_boy
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: "A versatile test fixtures replacement based on thoughtbot's factory_girl for Ruby."
  dev_url: https://github.com/FactoryBoy/factory_boy
  doc_url: https://factoryboy.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
