travis:
  secure:
    BINSTAR_TOKEN: Wb/HOxztOXV008reg2tyvbqZ0AQNoqEL20cckQk9VNZ74KKJSjl7/78TQ6WR5WA2qKLiKfCHemM0M9od0xtlKpzGqZUzi+whQDPSw3BHfzvs3EHTnv75VeRE/9wXHjvpyU6T6ngbC0MU/CfHwpjUTk1DKobQJNwDkd448DYQBgzDXo4bxWiVXo0Oraj1TUt7wZQbjk6WW3f4Ko6ZR22L50YiOGEbzX8tML3M1a/MhRl/xDHrmbSZp9Q8sn+VRtAfPyeLsTxbeIKB9mmf4MEYNjmh8Z/TaMWEXpANBk1ZE/T/24Lm0JijT0SbT60HVnsZXH/ottp3uPvCxpE2dqmwOPIZT9OloqBbP23X1pBYcSF1mFjoDSsp9iNfWxOykIGiNjJKLsFfNBfOESaskcRGbTTIlOBtkpaQFDLELuzRYA6c1tiSYxYm7zOG67k07jmOySaW7kf6ew5cvLS6SQrQuZQYIMUmgI08n0Ljj4M91kwZOt/VesPs55kH9i7BqRERf6bgNxiMa+Vqt2tXzVEkoGWp+FP1uVccAR+NmGDVjOImMmHLM0GatUM7DMrjU3tZi9ed2JhyATe+nQTOJyhdxnklx5UeG+cRArxYQVuoZYck8gLC5ojCM70XD0AmTIDs6RfsHW75aygRKuCzDK+YRbMMtozLGijrb5V6mZIqdRY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
